/* Generated By:JavaCC: Do not edit this line. LexIntConstants.java */
public interface LexIntConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int BINARY_LITERAL = 7;
  int REAL = 8;
  int IDENTIFIER = 9;
  int COMMENT = 10;
  int LETTER = 11;
  int DIGIT = 12;
  int EXPONENT = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<BINARY_LITERAL>",
    "<REAL>",
    "<IDENTIFIER>",
    "<COMMENT>",
    "<LETTER>",
    "<DIGIT>",
    "<EXPONENT>",
  };

}
