/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
public interface MiniJavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int LSQPAREN = 11;
  int RSQPAREN = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int SEMICOLON = 15;
  int DOT = 16;
  int ASSIGN = 17;
  int LT = 18;
  int PLUS = 19;
  int MINUS = 20;
  int AND = 21;
  int NOT = 22;
  int BOOLEAN = 23;
  int CLASS = 24;
  int INTERFACE = 25;
  int ELSE = 26;
  int EXTENDS = 27;
  int FALSE = 28;
  int IF = 29;
  int WHILE = 30;
  int REPEAT = 31;
  int UNTIL = 32;
  int INTEGER = 33;
  int LENGTH = 34;
  int MAIN = 35;
  int NEW = 36;
  int PUBLIC = 37;
  int RETURN = 38;
  int STATIC = 39;
  int STRING = 40;
  int THIS = 41;
  int TRUE = 42;
  int PRINT = 43;
  int VOID = 44;
  int INTEGER_LITERAL = 45;
  int IDENTIFIER = 46;
  int LETTER = 47;
  int DIGIT = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"&\"",
    "\"!\"",
    "\"boolean\"",
    "\"class\"",
    "\"interface\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"int\"",
    "\"length\"",
    "\"main\"",
    "\"new\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\"true\"",
    "\"System.out.println\"",
    "\"void\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\",\"",
    "\"&&\"",
    "\"*\"",
    "\"/\"",
  };

}
