/* Generated By:JavaCC: Do not edit this line. LiteralConstants.java */
public interface LiteralConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int DECIMAL_LITERAL = 7;
  int HEX_LITERAL = 8;
  int OCTAL_LITERAL = 9;
  int FLOATING_POINT_LITERAL = 10;
  int DIGITS = 11;
  int TYPESUFFIX = 12;
  int EXPONENT = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DIGITS>",
    "<TYPESUFFIX>",
    "<EXPONENT>",
  };

}
