/* Generated By:JavaCC: Do not edit this line. LexTestConstants.java */
public interface LexTestConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int FLOAT_LITERAL = 7;
  int PLUS = 8;
  int MINUS = 9;
  int MULT = 10;
  int DIV = 11;
  int IDENTIFIER = 12;
  int LETTER = 13;
  int DIGIT = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
