/* Generated By:JJTree: Do not edit this line. ASTOr.java */

public class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(TPLParser p, int id) {
    super(p, id);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    jjtGetChild(0).identification();
    jjtGetChild(1).identification();
  }

  public void typecheck () {
    jjtGetChild(0).typecheck();
    jjtGetChild(1).typecheck();
    if (!(jjtGetChild(0).GetNodeType() == TPLTypes.boolType &&
          jjtGetChild(1).GetNodeType() == TPLTypes.boolType))
       System.out.println("TPL Typechecker: or of non-bools.");
    NodeType = TPLTypes.boolType;
  }

  /* Added by DB to perform interpreting. */

  public void interpret()
  {
     boolean left, right;
     jjtGetChild(0).interpret();

     left = ((Boolean)stack.pop()).booleanValue();
     if (left)
     {
        stack.push(new Boolean(true));
        return;
     }

     jjtGetChild(1).interpret();
     right = ((Boolean)stack.pop()).booleanValue();
     stack.push(new Boolean(right));
  }

}
