/* Generated By:JJTree&JavaCC: Do not edit this line. TPLParserConstants.java */
public interface TPLParserConstants {

  int EOF = 0;
  int KEYSKIP = 6;
  int KEYWHILE = 7;
  int KEYFOR = 8;
  int KEYIF = 9;
  int KEYTHEN = 10;
  int KEYELSE = 11;
  int KEYREAD = 12;
  int KEYWRITE = 13;
  int KEYAND = 14;
  int KEYOR = 15;
  int KEYINT = 16;
  int KEYBOOL = 17;
  int INTEGER_LITERAL = 18;
  int KEYTRUE = 19;
  int KEYFALSE = 20;
  int IDENTIFIER = 21;
  int LETTER = 22;
  int DIGIT = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"skip\"",
    "\"while\"",
    "\"for\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"read\"",
    "\"write\"",
    "\"and\"",
    "\"or\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
