/* Generated By:JavaCC: Do not edit this line. cw1Constants.java */
public interface cw1Constants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int IDENTIFIER = 7;
  int HORROR = 8;
  int LETTER = 9;
  int DIGIT = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<HORROR>",
    "<LETTER>",
    "<DIGIT>",
  };

}
