/* Generated By:JJTree: Do not edit this line. ASTId.java */

public class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(TPLParser p, int id) {
    super(p, id);
  }

 /*
  * Field added to automatically generated class by DB to hold
  * name of identifier in node.
  */
  
  public String name;

  /*
  * Customized dump written by DB to show name in printed tree.
  * Overrides dump from SimpleNode. This is a leaf so no children to dump.
  */

  public void dump(String prefix) {
    System.out.print(toString(prefix));
    System.out.println(" "+name);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    if (!(symtab.containsKey(name))) { /* Insert if not declared. */
      System.out.println("TPL Identification: "+name+" not declared.");
      symtab.put (name, new IdSymbol (TPLTypes.intType, 0));
    }
  }

  public void typecheck () { /* Identification has inserted if not dec'd. */
     NodeType = ((IdSymbol)symtab.get(name)).type;
  }

}
