/* Generated By:JJTree: Do not edit this line. ASTNE.java */

public class ASTNE extends SimpleNode {
  public ASTNE(int id) {
    super(id);
  }

  public ASTNE(TPLParser p, int id) {
    super(p, id);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    jjtGetChild(0).identification();
    jjtGetChild(1).identification();
  }

  public void typecheck () {
    jjtGetChild(0).typecheck();
    jjtGetChild(1).typecheck();
    if (jjtGetChild(0).GetNodeType() != jjtGetChild(1).GetNodeType())
             System.out.println("TPL Typechecker: notequals of non-similar types .");
    NodeType = TPLTypes.boolType;
  }

}
