/* Generated By:JJTree: Do not edit this line. ASTOr.java */

public class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(TPLParser p, int id) {
    super(p, id);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    jjtGetChild(0).identification();
    jjtGetChild(1).identification();
  }

  public void typecheck () {
    jjtGetChild(0).typecheck();
    jjtGetChild(1).typecheck();
    if (!(jjtGetChild(0).GetNodeType() == TPLTypes.boolType &&
          jjtGetChild(1).GetNodeType() == TPLTypes.boolType))
       System.out.println("TPL Typechecker: or of non-bools.");
    NodeType = TPLTypes.boolType;
  }

}
