/* Generated By:JJTree: Do not edit this line. ASTReadStatement.java */

public class ASTReadStatement extends SimpleNode {
  public ASTReadStatement(int id) {
    super(id);
  }

  public ASTReadStatement(TPLParser p, int id) {
    super(p, id);
  }

 /*
  * Field added to automatically generated class by DB to hold
  * name of variable in node.
  */

  public String name;

  /*
  * Customized dump written by DB to show name in printed tree.
  * Overrides dump from SimpleNode. This is a leaf so no children to dump.
  */

  public void dump(String prefix) {
    System.out.print(toString(prefix));
    System.out.println(" "+name);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    if (!(symtab.containsKey(name)))
      System.out.println("TPL Identification: "+name+" not declared (read).");
  }

  public void typecheck () {
    NodeType = TPLTypes.stmType;
  }
}
