/* Generated By:JJTree: Do not edit this line. ASTStatementBlock.java */

public class ASTStatementBlock extends SimpleNode {
  public ASTStatementBlock(int id) {
    super(id);
  }

  public ASTStatementBlock(TPLParser p, int id) {
    super(p, id);
  }


  /* Added by DB to do identification and type-checking. */

  public void identification()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).identification();
  }

  public void typecheck()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).typecheck();

     NodeType = TPLTypes.stmType;
  }
}
