/* Generated By:JavaCC: Do not edit this line. LexTestConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexTestConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int END_INPUT = 3;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 4;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULT = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<END_INPUT>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
