/* Generated By:JJTree: Do not edit this line. ASTAssignStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignStatement extends SimpleNode {
  public ASTAssignStatement(int id) {
    super(id);
  }

  public ASTAssignStatement(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3dc4cf990f75bc1bbc51b43e8a4af561 (do not edit this line) */
