/* Generated By:JJTree: Do not edit this line. ASTEQ.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQ extends SimpleNode {
  public ASTEQ(int id) {
    super(id);
  }

  public ASTEQ(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9e0dc2a16740d5357d7ba8d468cdede (do not edit this line) */
