/* Generated By:JJTree: Do not edit this line. ASTGE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGE extends SimpleNode {
  public ASTGE(int id) {
    super(id);
  }

  public ASTGE(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fadefb984f33d52b10ffb99014f3c435 (do not edit this line) */
