/* Generated By:JJTree: Do not edit this line. ASTGT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGT extends SimpleNode {
  public ASTGT(int id) {
    super(id);
  }

  public ASTGT(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11a333baaa1f58069e5b59550afbf9da (do not edit this line) */
