/* Generated By:JJTree: Do not edit this line. ASTIntConst.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntConst extends SimpleNode {
  public ASTIntConst(int id) {
    super(id);
  }

  public ASTIntConst(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8be077c9530de1f86405a014fa56755e (do not edit this line) */
