/* Generated By:JJTree: Do not edit this line. ASTLT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19a81b3131a74cb655b1f74a5425fd62 (do not edit this line) */
