/* Generated By:JJTree: Do not edit this line. ASTLE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLE extends SimpleNode {
  public ASTLE(int id) {
    super(id);
  }

  public ASTLE(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c83833805dce3046106e56271b8c7750 (do not edit this line) */
