/* Generated By:JJTree: Do not edit this line. ASTMul.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMul extends SimpleNode {
  public ASTMul(int id) {
    super(id);
  }

  public ASTMul(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df546eddfe1b273f1c38585969733c38 (do not edit this line) */
