/* Generated By:JJTree: Do not edit this line. ASTReadStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReadStatement extends SimpleNode {
  public ASTReadStatement(int id) {
    super(id);
  }

  public ASTReadStatement(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d80e5abf6473c620c0ebf0f5bc42493 (do not edit this line) */
