/* Generated By:JJTree: Do not edit this line. ASTStatementBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementBlock extends SimpleNode {
  public ASTStatementBlock(int id) {
    super(id);
  }

  public ASTStatementBlock(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=885faa7e983fff4bdfa74b090d62b19a (do not edit this line) */
