/* Generated By:JJTree: Do not edit this line. ASTSkipStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSkipStatement extends SimpleNode {
  public ASTSkipStatement(int id) {
    super(id);
  }

  public ASTSkipStatement(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fecf2e6fd01a2326f75284b97d77a0ae (do not edit this line) */
