/* Generated By:JJTree: Do not edit this line. ASTWriteStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWriteStatement extends SimpleNode {
  public ASTWriteStatement(int id) {
    super(id);
  }

  public ASTWriteStatement(TPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e642a065a2b817bae7214826c539d7fb (do not edit this line) */
