/* Generated By:JavaCC: Do not edit this line. TPLParserTreeConstants.java Version 5.0 */
public interface TPLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTSKIPSTATEMENT = 3;
  public int JJTASSIGNSTATEMENT = 4;
  public int JJTIFSTATEMENT = 5;
  public int JJTWHILESTATEMENT = 6;
  public int JJTSTATEMENTBLOCK = 7;
  public int JJTREADSTATEMENT = 8;
  public int JJTWRITESTATEMENT = 9;
  public int JJTOR = 10;
  public int JJTAND = 11;
  public int JJTEQ = 12;
  public int JJTNE = 13;
  public int JJTLT = 14;
  public int JJTGT = 15;
  public int JJTLE = 16;
  public int JJTGE = 17;
  public int JJTADD = 18;
  public int JJTSUBTRACT = 19;
  public int JJTMUL = 20;
  public int JJTDIV = 21;
  public int JJTID = 22;
  public int JJTINTCONST = 23;
  public int JJTTRUE = 24;
  public int JJTFALSE = 25;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDeclaration",
    "void",
    "SkipStatement",
    "AssignStatement",
    "IfStatement",
    "WhileStatement",
    "StatementBlock",
    "ReadStatement",
    "WriteStatement",
    "Or",
    "And",
    "EQ",
    "NE",
    "LT",
    "GT",
    "LE",
    "GE",
    "Add",
    "Subtract",
    "Mul",
    "Div",
    "Id",
    "IntConst",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=0e1f3bd2ced15c04de12e1524eef1663 (do not edit this line) */
