/* Generated By:JJTree&JavaCC: Do not edit this line. TPLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEYSKIP = 6;
  /** RegularExpression Id. */
  int KEYWHILE = 7;
  /** RegularExpression Id. */
  int KEYIF = 8;
  /** RegularExpression Id. */
  int KEYTHEN = 9;
  /** RegularExpression Id. */
  int KEYELSE = 10;
  /** RegularExpression Id. */
  int KEYREAD = 11;
  /** RegularExpression Id. */
  int KEYWRITE = 12;
  /** RegularExpression Id. */
  int KEYAND = 13;
  /** RegularExpression Id. */
  int KEYOR = 14;
  /** RegularExpression Id. */
  int KEYINT = 15;
  /** RegularExpression Id. */
  int KEYBOOL = 16;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 17;
  /** RegularExpression Id. */
  int KEYTRUE = 18;
  /** RegularExpression Id. */
  int KEYFALSE = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"skip\"",
    "\"while\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"read\"",
    "\"write\"",
    "\"and\"",
    "\"or\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
