/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java */

public class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(TPLParser p, int id) {
    super(p, id);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    jjtGetChild(0).identification();
    jjtGetChild(1).identification();
  }

  public void typecheck () {
    jjtGetChild(0).typecheck();
    jjtGetChild(1).typecheck();

    if (jjtGetChild(0).GetNodeType() != TPLTypes.boolType)
       System.out.println("TPL Typechecker: while statement condition non-bool");

    NodeType = TPLTypes.stmType;
  }

  /* Added by DB to perform interpreting. */

  public void interpret () {
     do {
       jjtGetChild(0).interpret();

       if (((Boolean)stack.pop()).booleanValue())
          jjtGetChild(1).interpret();
       else
          break;
    } while (true);
  }



}
