/* Generated By:JJTree: Do not edit this line. ASTTrue.java */

public class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(TPLParser p, int id) {
    super(p, id);
  }

  public void typecheck(){
    NodeType = TPLTypes.boolType;
  }

  /* Added by DB to perform interpreting. */

  public void interpret () {
    stack.push(new Boolean(true));
  }


}
