/* Generated By:JJTree: Do not edit this line. ASTDivExp.java */

public class ASTDivExp extends SimpleNode {
  public ASTDivExp(int id) {
    super(id);
  }

  public ASTDivExp(ExpParser p, int id) {
    super(p, id);
  }


    public int evaluate() {
	return jjtGetChild(0).evaluate() / jjtGetChild(1).evaluate();  
    }



}
