/* Generated By:JJTree: Do not edit this line. ASTS.java */

public class ASTS extends SimpleNode {
  public ASTS(int id) {
    super(id);
  }

  public ASTS(ExpParser p, int id) {
    super(p, id);
  }

}
