/* Generated By:JJTree: Do not edit this line. ASTTimesExp.java */

public class ASTTimesExp extends SimpleNode {
  public ASTTimesExp(int id) {
    super(id);
  }

  public ASTTimesExp(ExpParser p, int id) {
    super(p, id);
  }

    public int evaluate() {
	return jjtGetChild(0).evaluate() * jjtGetChild(1).evaluate();  
    }



}
