/* Generated By:JavaCC: Do not edit this line. ExpParserTreeConstants.java Version 5.0 */
public interface ExpParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTPLUSEXP = 1;
  public int JJTMINUSEXP = 2;
  public int JJTTIMESEXP = 3;
  public int JJTDIVEXP = 4;
  public int JJTNUMEXP = 5;


  public String[] jjtNodeName = {
    "void",
    "PlusExp",
    "MinusExp",
    "TimesExp",
    "DivExp",
    "NumExp",
  };
}
/* JavaCC - OriginalChecksum=68ef33e9d3acd20c22ce88fbbc2c2f5a (do not edit this line) */
