/* Generated By:JavaCC: Do not edit this line. cw1Constants.java */
public interface cw1Constants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int MYID2 = 7;
  int MYID = 8;
  int MYID3 = 9;
  int IDENTIFIER = 10;
  int RATIONAL = 11;
  int HORROR = 12;
  int LETTER = 13;
  int DIGIT = 14;
  int ALPHA = 15;
  int NUMERIC = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<MYID2>",
    "<MYID>",
    "<MYID3>",
    "<IDENTIFIER>",
    "<RATIONAL>",
    "<HORROR>",
    "<LETTER>",
    "<DIGIT>",
    "\"abdt\"",
    "\"117\"",
  };

}
