/* Generated By:JavaCC: Do not edit this line. LexTestConstants.java */
public interface LexTestConstants {

  int EOF = 0;
  int BINARY_LITERAL = 6;
  int OCTAL_LITERAL = 7;
  int DECIMAL = 8;
  int HEX_LITERAL = 9;
  int FLOATING_POINT_LITERAL = 10;
  int EXPONENT = 11;
  int SINGLE_LINE_COMMENT = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<BINARY_LITERAL>",
    "<OCTAL_LITERAL>",
    "<DECIMAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<SINGLE_LINE_COMMENT>",
  };

}
