/* Generated By:JJTree: Do not edit this line. ASTAssignStatement.java */

public class ASTAssignStatement extends SimpleNode {
  public ASTAssignStatement(int id) {
    super(id);
  }

  public ASTAssignStatement(TPLParser p, int id) {
    super(p, id);
  }

}
