/* Generated By:JJTree: Do not edit this line. ASTAnd.java */

public class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(TPLParser p, int id) {
    super(p, id);
  }

}
