/* Generated By:JJTree: Do not edit this line. ASTDiv.java */

public class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(TPLParser p, int id) {
    super(p, id);
  }

}
