/* Generated By:JJTree: Do not edit this line. ASTEQ.java */

public class ASTEQ extends SimpleNode {
  public ASTEQ(int id) {
    super(id);
  }

  public ASTEQ(TPLParser p, int id) {
    super(p, id);
  }

}
