/* Generated By:JJTree: Do not edit this line. ASTGE.java */

public class ASTGE extends SimpleNode {
  public ASTGE(int id) {
    super(id);
  }

  public ASTGE(TPLParser p, int id) {
    super(p, id);
  }

}
