/* Generated By:JJTree: Do not edit this line. ASTGT.java */

public class ASTGT extends SimpleNode {
  public ASTGT(int id) {
    super(id);
  }

  public ASTGT(TPLParser p, int id) {
    super(p, id);
  }

}
