/* Generated By:JJTree: Do not edit this line. ASTIntConst.java */

public class ASTIntConst extends SimpleNode {
  public ASTIntConst(int id) {
    super(id);
  }

  public ASTIntConst(TPLParser p, int id) {
    super(p, id);
  }

    // Igor
    int val;

}
