/* Generated By:JJTree: Do not edit this line. ASTLE.java */

public class ASTLE extends SimpleNode {
  public ASTLE(int id) {
    super(id);
  }

  public ASTLE(TPLParser p, int id) {
    super(p, id);
  }

}
