/* Generated By:JJTree: Do not edit this line. ASTLT.java */

public class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(TPLParser p, int id) {
    super(p, id);
  }

}
