/* Generated By:JJTree: Do not edit this line. ASTMul.java */

public class ASTMul extends SimpleNode {
  public ASTMul(int id) {
    super(id);
  }

  public ASTMul(TPLParser p, int id) {
    super(p, id);
  }

}
