/* Generated By:JJTree: Do not edit this line. ASTNE.java */

public class ASTNE extends SimpleNode {
  public ASTNE(int id) {
    super(id);
  }

  public ASTNE(TPLParser p, int id) {
    super(p, id);
  }

}
