/* Generated By:JJTree: Do not edit this line. ASTSubtract.java */

public class ASTSubtract extends SimpleNode {
  public ASTSubtract(int id) {
    super(id);
  }

  public ASTSubtract(TPLParser p, int id) {
    super(p, id);
  }

}
