/* Generated By:JJTree: Do not edit this line. ASTStatementBlock.java */

public class ASTStatementBlock extends SimpleNode {
  public ASTStatementBlock(int id) {
    super(id);
  }

  public ASTStatementBlock(TPLParser p, int id) {
    super(p, id);
  }

}
