/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java */

public class ASTVarDeclaration extends SimpleNode {
  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(TPLParser p, int id) {
    super(p, id);
  }

    // Added by Igor Siveroni
    public int type;
    public String name;

}
