/* Generated By:JJTree: Do not edit this line. ASTWriteStatement.java */

public class ASTWriteStatement extends SimpleNode {
  public ASTWriteStatement(int id) {
    super(id);
  }

  public ASTWriteStatement(TPLParser p, int id) {
    super(p, id);
  }

    //added by Igor
    public String name;

}
