/* Generated By:JavaCC: Do not edit this line. LexTestConstants.java */
public interface LexTestConstants {

  int EOF = 0;
  int KEYWHILE = 6;
  int KEYENDWHILE = 7;
  int INTEGER_LITERAL = 8;
  int REAL = 9;
  int KEYTRUE = 10;
  int KEYFALSE = 11;
  int IDENTIFIER = 12;
  int LETTER = 13;
  int DIGIT = 14;
  int EXPONENT = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"while\"",
    "\"endwhile\"",
    "<INTEGER_LITERAL>",
    "<REAL>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<EXPONENT>",
  };

}
