/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int EOL = 4;
  int PLUS = 5;
  int MINUS = 6;
  int MULTIPLY = 7;
  int DIVIDE = 8;
  int CONSTANT = 9;
  int ID = 10;
  int DIGIT = 11;
  int LETTER = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<CONSTANT>",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "\";\"",
    "\":=\"",
    "\"print(\"",
    "\")\"",
    "\",\"",
    "\"(\"",
  };

}
