/* Generated By:JJTree: Do not edit this line. ASTMinusExp.java */

public class ASTMinusExp extends SimpleNode {
  public ASTMinusExp(int id) {
    super(id);
  }

  public ASTMinusExp(ExpParser p, int id) {
    super(p, id);
  }

}
