/* Generated By:JJTree: Do not edit this line. ASTNumExp.java */

public class ASTNumExp extends SimpleNode {
  public ASTNumExp(int id) {
    super(id);
  }

  public ASTNumExp(ExpParser p, int id) {
    super(p, id);
  }

}
