/* Generated By:JJTree: Do not edit this line. ASTPlusExp.java */

public class ASTPlusExp extends SimpleNode {
  public ASTPlusExp(int id) {
    super(id);
  }

  public ASTPlusExp(ExpParser p, int id) {
    super(p, id);
  }

}
