/* Generated By:JJTree: Do not edit this line. ./ExpParserTreeConstants.java */

public interface ExpParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTPLUSEXP = 1;
  public int JJTMINUSEXP = 2;
  public int JJTTIMESEXP = 3;
  public int JJTDIVEXP = 4;
  public int JJTNUMEXP = 5;


  public String[] jjtNodeName = {
    "void",
    "PlusExp",
    "MinusExp",
    "TimesExp",
    "DivExp",
    "NumExp",
  };
}
