/* Generated By:JJTree: Do not edit this line. ASTNE.java */

public class ASTNE extends SimpleNode {
  public ASTNE(int id) {
    super(id);
  }

  public ASTNE(TPLParser p, int id) {
    super(p, id);
  }

  /* Added by DB to perform identification and type checking. */

  public void identification () {
    jjtGetChild(0).identification();
    jjtGetChild(1).identification();
  }

  public void typecheck () {
    jjtGetChild(0).typecheck();
    jjtGetChild(1).typecheck();
    if (jjtGetChild(0).GetNodeType() != jjtGetChild(1).GetNodeType())
             System.out.println("TPL Typechecker: notequals of non-similar types .");
    NodeType = TPLTypes.boolType;
  }

  /* Added by DB to perform interpreting. */

  public void interpret () {
    boolean result;
    int ileft, iright;
    boolean bleft, bright;
    jjtGetChild(0).interpret();
    jjtGetChild(1).interpret();

    if (stack.peek() instanceof Integer) {
      iright = ((Integer)stack.pop()).intValue();
      ileft = ((Integer)stack.pop()).intValue();
      stack.push(new Boolean(iright!=ileft));
    }
    else {
      bright = ((Boolean)stack.pop()).booleanValue();
      bleft = ((Boolean)stack.pop()).booleanValue();
      stack.push(new Boolean(bright!=bleft));
    }
  }

}
