/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java */

public class ASTVarDeclaration extends SimpleNode {

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(TPLParser p, int id) {
    super(p, id);
  }

  /* 
   * Fields added to automatically generated class by DB to hold type and
   * name of variable in node.
   */

  public int type; 
  public String name;

  /*
  * Customized dump written by DB to show name and type in printed tree.
  * Overrides dump from SimpleNode. This is a leaf so no children to dump.
  */

  public void dump(String prefix) {
    System.out.print(toString(prefix));
    System.out.println(" "+name+" "+((type==TPLTypes.intType)?"INT":"BOOL"));
  }

  /* Added by DB to perform identification and type checking. */
 
  public void identification () {
    if (type == TPLTypes.boolType)
      symtab.put (name, new IdSymbol (type, false)); 
    else
      symtab.put (name, new IdSymbol (type, 0));
  }

  public void typecheck () {
    NodeType = TPLTypes.decType;
  }   

  /* Added by DB to perform interpretation. */

  public void interpret () { /* Do nothing: identification initialises table. */
  }
}

