/* Generated By:JavaCC: Do not edit this line. cw1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface cw1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int RATIONAL = 7;
  /** RegularExpression Id. */
  int MYID = 8;
  /** RegularExpression Id. */
  int MYID3 = 9;
  /** RegularExpression Id. */
  int MYID2 = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int HORROR = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int UNSIGNED_INT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<RATIONAL>",
    "\"sbbc287\"",
    "<MYID3>",
    "<MYID2>",
    "<IDENTIFIER>",
    "<HORROR>",
    "<LETTER>",
    "<DIGIT>",
    "<UNSIGNED_INT>",
  };

}
