/* Generated By:JJTree: Do not edit this line. ASTDivExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDivExp extends SimpleNode {
  public ASTDivExp(int id) {
    super(id);
  }

  public ASTDivExp(ExpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1381a94082887ec7249dc8850905e6f (do not edit this line) */
