/* Generated By:JJTree: Do not edit this line. ASTMinusExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinusExp extends SimpleNode {
  public ASTMinusExp(int id) {
    super(id);
  }

  public ASTMinusExp(ExpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd776183f21722c23765ce259826e278 (do not edit this line) */
