/* Generated By:JJTree: Do not edit this line. ASTNumExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNumExp extends SimpleNode {
  public ASTNumExp(int id) {
    super(id);
  }

  public ASTNumExp(ExpParser p, int id) {
    super(p, id);
  }

    public int val;

    public void dump(String prefix) {  
	System.out.print(toString(prefix));
	System.out.println(" "+val);
    }

}
/* JavaCC - OriginalChecksum=e50510d216fde6fabad9a1f067215f65 (do not edit this line) */
