/* Generated By:JJTree: Do not edit this line. ASTPlusExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPlusExp extends SimpleNode {
  public ASTPlusExp(int id) {
    super(id);
  }

  public ASTPlusExp(ExpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7afeb96d6f19f92767b8d8ed544dce26 (do not edit this line) */
