/* Generated By:JJTree: Do not edit this line. ASTTimesExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTimesExp extends SimpleNode {
  public ASTTimesExp(int id) {
    super(id);
  }

  public ASTTimesExp(ExpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10aca7b3371a41db92768e50bb64b599 (do not edit this line) */
