/* Generated By:JavaCC: Do not edit this line. LexTestConstants.java */
public interface LexTestConstants {

  int EOF = 0;
  int KEYWHILE = 6;
  int INTEGER_LITERAL = 7;
  int KEYTRUE = 8;
  int KEYFALSE = 9;
  int IDENTIFIER = 10;
  int COMMENT = 11;
  int HORROR = 12;
  int LETTER = 13;
  int DIGIT = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<COMMENT>",
    "<HORROR>",
    "<LETTER>",
    "<DIGIT>",
  };

}
