/* Generated By:JavaCC: Do not edit this line. ExpConstants.java */
public interface ExpConstants {

  int EOF = 0;
  int NUM = 4;
  int EOL = 5;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<NUM>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
