/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int VOID = 5;
  int MAIN = 6;
  int TRUE = 7;
  int FALSE = 8;
  int PLUS = 9;
  int MINUS = 10;
  int TIMES = 11;
  int DIV = 12;
  int GT = 13;
  int GEQ = 14;
  int EQ = 15;
  int NOT = 16;
  int AND = 17;
  int OR = 18;
  int PRINT = 19;
  int IF = 20;
  int REPEAT = 21;
  int UNTIL = 22;
  int THEN = 23;
  int ELSE = 24;
  int INTEGER = 25;
  int WHILE = 26;
  int MODULO = 27;
  int INTLITERAL = 28;
  int ID = 29;
  int DIGIT = 30;
  int LETTER = 31;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"void\"",
    "\"main\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!\"",
    "\"and\"",
    "\"or\"",
    "\"print\"",
    "\"if\"",
    "\"repeat\"",
    "\"until\"",
    "\"then\"",
    "\"else\"",
    "\"int\"",
    "\"while\"",
    "\"%\"",
    "<INTLITERAL>",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":=\"",
  };

}
